#!/bin/bash

if [[ -z "$1" ]]; then
    startDir="$HOME"
else
    startDir="$1"
fi

ignore_dirs=".git,host,node_modules,.idea,.m2,pkg,.vscode-server,.cache"
chosen=$(fzf --walker="file,dir,follow,hidden" --walker-root="$startDir" --walker-skip="$ignore_dirs")

if [[ -z "$chosen" ]]; then
    exit 0
elif [[ -d "$chosen" ]]; then
    echo "$chosen"
else
    dirname "$chosen"
fi
