#!/bin/bash

if [[ -z "$1" ]]; then
    startDir="$HOME"
else
    startDir="$1"
fi

chosen=$(fzf --walker="file,dir,follow,hidden" --walker-root="$startDir" --walker-skip=".git,node_modules,.idea")

if [[ -z "$chosen" ]]; then
    exit 0
elif [[ -d "$chosen" ]]; then
    echo "$chosen"
else
    dirname "$chosen"
fi
