#!/bin/bash

if [[ -z "$1" ]]; then
    startDir="$HOME"
else
    startDir="$1"
fi

chosen=$(fzf --walker="file,dir,follow,hidden" --walker-root="$startDir" --walker-skip=".git,node_modules,.idea")
echo "Chosen: $chosen"

if [[ -z "$chosen" ]]; then
    echo "Chosen was empty."
    exit 0
fi

if [[ -d "$chosen" ]]; then
    cd "$chosen"
else
    cd $(dirname "$chosen")
fi
