#!/bin/bash

set -e

# ======================================================================================================================
# ==> Constants
MAIN_HOST_DIR="/mnt/c/Users/Max"



# ======================================================================================================================
# ==> Configure home with host links.
echo Checking host softlinks...
test ! -L "$HOME/host" && ln -s "$MAIN_HOST_DIR" "$HOME/host"
#test ! -L "$HOME/IdeaProjects" && ln -s "$MAIN_HOST_DIR/IdeaProjects" "$HOME/IdeaProjects"



# ======================================================================================================================
# ==> Configure git to use host credential manager.
echo Binding git credential manager to host...
git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"



# ======================================================================================================================
# ==> Configure home with normal dirs.
test ! -d "$HOME/Downloads" && mkdir "$HOME/Downloads"
test ! -d "$HOME/IdeaProjects" && mkdir "$HOME/IdeaProjects"
test ! -d "$HOME/scripts" && mkdir "$HOME/scripts"
test ! -d "$HOME/temp" && mkdir "$HOME/temp"
#test ! -d "$HOME/dev" && mkdir "$HOME/dev"



# ======================================================================================================================
# ==> Configure bash.
# Install git so PS1 works with Git.
echo Getting bash config...
#sudo dnf install -y git-all
cp -f "$HOME/straight-and-narrow/.bashrc" "$HOME/.bashrc"
cp -f "$HOME/straight-and-narrow/.mkps1" "$HOME/.mkps1"
cp -f "$HOME/straight-and-narrow/.bash_profile" "$HOME/.bash_profile"
cp -f "$HOME/straight-and-narrow/.bash_aliases" "$HOME/.bash_aliases"
echo Sourcing bashrc...
source "$HOME/.bashrc"
